#!/bin/sh
#===============================================================================
#
#  sysinfo
#
#  Copyright (C) 2016-2018 by Digi International Inc.
#  All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License version 2 as published by
#  the Free Software Foundation.
#
#
#  !Description: System information gather script
#
#===============================================================================

FW_PRINTENV="$(which fw_printenv)"

make_report(){
	echo "--------------------------------------"
	echo "-                                    -"
	echo "-               Uptime               -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	uptime
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-          Kernel version            -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	uname -a
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-             OS release             -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	if [ -f "/etc/os-release" ]; then
		cat /etc/os-release
	else
		echo "[NOT FOUND] /etc/os-release"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-         Build configurations       -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	if [ -f "/etc/build" ]; then
		cat /etc/build
	else
		echo "[NOT FOUND] /etc/build"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-      U-boot saved environment      -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	if [ -x "${FW_PRINTENV}" ]; then
		${FW_PRINTENV}
	else
		echo "[NOT FOUND] fw_printenv"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-          Linux boot log            -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	dmesg
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-       Log files from /var/log      -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	for f in $(find /var/log/ -name "*.log"); do
		echo "${f} FILE";
		echo "---------------------------------------";
		cat ${f};
		printf "\n\n"
	done
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-         /var/log/messages          -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	if [ -f "/var/log/messages" ]; then
		cat /var/log/messages
	else
		echo "[NOT FOUND] /var/log/messages"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-     Linux kernel configuration     -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	if [ -f "/proc/config.gz" ]; then
		zcat /proc/config.gz
	else
		echo "[NOT FOUND] /proc/config.gz"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-         Memory consumption         -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	free
	printf "\n"
	cat /proc/meminfo
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-          Running processes         -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	ps -l
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-              Mounts                -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	mount
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-            Disk layout             -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	fdisk -l
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-            Opened ports            -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	netstat -n -a
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-               Routes               -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	route -n
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-        Network configuration       -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	ifconfig -a
	printf "\n"
	ip link show
	printf "\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-       Wireless configuration       -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""
	wpa_supplicant -v 2>/dev/null
	echo ""
	if [ -f "/etc/wpa_supplicant.conf" ]; then
		echo "wpa_supplicant.conf:"
		cat "/etc/wpa_supplicant.conf"
	else
		echo "[NOT FOUND] /etc/wpa_supplicant.conf"
	fi
	echo ""
	if [ -f "/etc/wpa_supplicant_p2p.conf" ]; then
		echo "wpa_supplicant_p2p.conf:"
		cat "/etc/wpa_supplicant_p2p.conf"
	else
		echo "[NOT FOUND] /etc/wpa_supplicant_p2p.conf"
	fi
	echo ""

	hostapd -v 2>&1
	echo ""
	if [ -f "/etc/hostapd.conf" ]; then
		echo "hostapd.conf:"
		cat "/etc/hostapd.conf"
	else
		echo "[NOT FOUND] hostapd.conf"
	fi
	echo ""
	if [ -f "/etc/hostapd_wlan0.conf" ]; then
		echo "hostapd_wlan0.conf:"
		cat "/etc/hostapd_wlan0.conf"
	else
		echo "[NOT FOUND] /etc/hostapd_wlan0.conf"
	fi
	echo ""
	if [ -f "/etc/hostapd_wlan1.conf" ]; then
		echo "hostapd_wlan1.conf:"
		cat "/etc/hostapd_wlan1.conf"
	else
		echo "[NOT FOUND] /etc/hostapd_wlan1.conf"
	fi
	printf "\n\n"

	echo "--------------------------------------"
	echo "-                                    -"
	echo "-             Fuses/OTP              -"
	echo "-                                    -"
	echo "--------------------------------------"
	echo ""

	CFG4="$(cat /sys/fsl_otp/HW_OCOTP_CFG4)"
	CFG5="$(cat /sys/fsl_otp/HW_OCOTP_CFG5)"
	MAC0="$(cat /sys/fsl_otp/HW_OCOTP_MAC0 | \
		sed -ne 's,^0x\([[:xdigit:]]\{2\}\)\([[:xdigit:]]\{2\}\)\([[:xdigit:]]\{2\}\)\([[:xdigit:]]\{2\}\)$,\1:\2:\3:\4,g;T;p')"
	MAC1="$(cat /sys/fsl_otp/HW_OCOTP_MAC1 | sed -ne 's,^0x\([[:xdigit:]]\{2\}\)\([[:xdigit:]]\{2\}\)$,\1:\2:,g;T;p' )"

	echo "Fused MAC: ${MAC1}${MAC0}"
	echo "Register CFG4: ${CFG4}"
	echo "Register CFG5: ${CFG5}"
	printf "\n"

	echo "-------------End of report------------"
}


DISTRO="$(sed -ne 's,DISTRO = \(.*\)$,\1,g;T;p' /etc/build)"
DISTRO_VERSION="$(sed -ne 's,DISTRO_VERSION = \(.*\)$,\1,g;T;p' /etc/build)"
UBOOT_PARTITION="/dev/mmcblk3boot0"
UBOOT_VERSION="$(strings ${UBOOT_PARTITION} | grep "U-Boot 20")"
BOARD_BASE="$(${FW_PRINTENV} | sed -ne 's,board_name=\(.*\)$,\1,g;T;p')"

EEPROM_NODE="/sys/bus/i2c/devices/0-0052/eeprom"
if ! [ -f ${EEPROM_NODE} ]; then
	EEPROM_NODE="/sys/bus/i2c/devices/2-0052/eeprom"
fi

dd if=${EEPROM_NODE} bs=1k count=1 2>/dev/null | strings -n 1 -o > /tmp/eeprom
DEVICE_ENUM="$(cat /tmp/eeprom | sed -ne 's,^[[:space:]]*30 \(.*\).*$,\1,g;T;p')"
DEVICE_SN="$(cat /tmp/eeprom | sed -ne 's,^[[:space:]]*54 \(.*\).*$,\1,g;T;p')"
DEVICE_REV="$(cat /tmp/eeprom | sed -ne 's,^[[:space:]]*42 \(.*\).*$,\1,g;T;p')"
DISPLAYSTRING="$(cat /tmp/eeprom | sed -ne 's,^[[:space:]]*1230 \(.*\).*$,\1,g;T;p')"

DATE="$(date "+%Y%m%d%H%M%S")"
FILE="/tmp/sysinfo-${DEY_VERSION}-${BOARD_SN}-${DATE}.txt"
printf "\n\n"

(
	echo "-------------------------------------"
	echo "-                                   -"
	echo "-         ENVIRONMENT TABLE         -"
	echo "-                                   -"
	echo "-------------------------------------"
	echo ""

	echo "||*Component*    ||*Version*"
	echo "|| DUT           || E#: ${DEVICE_ENUM}, SN: ${DEVICE_SN}, REV: ${DEVICE_REV}, Board: ${BOARD_BASE}"
	echo "|| U-Boot        || ${UBOOT_VERSION}"
	echo "|| Firmware      || ${DISTRO}-${DISTRO_VERSION}-$(cat /etc/version)"
	echo "|| Kernel        || $(uname -a)"
	echo "|| meta-ces      || $(sed -ne '/^meta-ces/s,.*= \(.*\)$,\1,g;T;p' /etc/build)"
	echo "|| Displaystring || ${DISPLAYSTRING}"
	printf "\n\n"
) | tee ${FILE}

make_report >> ${FILE}
gzip ${FILE}
echo "Report generated in ${FILE}.gz"
printf "\n\n"
