#!/bin/sh

# Resistive type touch screen needs calibration
# Check for 0eef vendor USB ID for egalax usb controller
lsusb | grep 0eef:
RESISTIVE=echo $?

if [ "$RESISTIVE" -eq "1" ]; then
	/usr/bin/xinput_calibrator_once.sh
fi

export CHROME_DEVEL_SANDBOX=/usr/sbin/chrome-devel-sandbox
export LD_LIBRARY_PATH=/usr/lib/chromium

CHROMIUM_TMP=/tmp/chromium

CHROME_EXTRA_ARGS=""

if [ -d ${HOME}/.chromium ] ; then
	rm -rf ${HOME}/.chromium
fi
if [ -d $CHROMIUM_TMP ] ; then
	rm -rf $CHROMIUM_TMP/*
else
	mkdir -p $CHROMIUM_TMP
fi

CHROME_EXTRA_ARGS="${CHROME_EXTRA_ARGS} --user-data-dir=${CHROMIUM_TMP} --disk-cache-dir=${CHROMIUM_TMP}"

if [ -z "$@" ]; then
	source /etc/default/chromium-autostart
	ARGS=$START_URL
else
	ARGS=$@
fi

# Calculate window size dynamically instead of hardcoding for each screen size
SWIDTH=`fbset | grep geometry | awk -F ' ' '{print $2}'`
SHEIGHT=`fbset | grep geometry | awk -F ' ' '{print $3}'`
WWIDTH=`expr $SWIDTH + 1`
WHEIGHT=`expr $SHEIGHT + 1`

/usr/bin/chromium/chrome --app --disable-application-cache --disable-desktop-notifications --disable-translate --disable-infobars --no-first-run --disable-suggestion-service --disable-save-password-bubble --disable-new-tab-first-run --use-pure-views --kiosk --no-message-box --start-maximized --disable-plugins --disable-extensions --start-fullscreen --enable-offline-auto-reload-visible-only --disable-desktop-notifications --disable-infobars --overscroll-history-navigation=0 --window-size=$WWIDTH,$WHEIGHT --window-position=0,0 ${CHROME_EXTRA_ARGS} $ARGS
